import type { Metadata } from "next";
import "./globals.scss";
import { SUSE } from 'next/font/google'
import Sidebar from '@/components/layout/sidebar/Sidebar'
import { Layout } from '@/components/layout/Layout'

const inter = SUSE({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}
      >
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
